In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import torch
import numpy as np

# 2.2 파이토치 기초 문법

## 2.2.1 텐서 다루기

### 텐서 생성 및 변환
* 파이토치의 가장 기본이 되는 데이터 구조 (NumPy ndarray와 비슷)
* GPU에서의 연산 가능

* 텐서 생성 : torch.tensor()
* GPU에 텐서 생성 : device="cuda:0"
* dtype 설정 : dtype=torch.float64


In [ ]:
# 텐서 생성
print(torch.tensor([[1,2],[3,4]]))                                              # 2차원 형태의 텐서 생성
print(torch.tensor([[1,2],[3,4]], device="cuda:0"))                             # GPU에 텐서 생성
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))                         # dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:
# 텐서를 ndarray로 변환
temp1 = torch.tensor([[1,2],[3,4]])
print(temp1.numpy())                                                            # 텐서를 ndarray로 변환

temp2 = torch.tensor([[1,2],[3,4]], device="cuda:0")                            # GPU에 텐서 생성
print(temp2.to("cpu").numpy())                                                  # GPU상의 텐서를 CPU의 텐서로 변환한 후 ndarray로 변환

print(type(temp1.numpy()), type(temp2.to("cpu").numpy()))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


### 텐서의 인덱스 조작
* index 지정, slicing 가능
* tensor dtype
  * torch.FloatTensor : 32bit float
  * torch.DoubleTensor : 64bit float
  * torch.LongTensor : 64bit signed int
  * 이외에도 다양한 유형의 텐서 존재...


In [ ]:
# 텐서의 인덱스 조작
temp = torch.FloatTensor([1,2,3,4,5,6,7])                                       # pytorch로 1차원 벡터 생성
print(temp[0],temp[1],temp[-1])                                                 # index로 접근
print(temp[2:5],temp[4:-1])                                                     # slice로 접근

# + torch.FloatTensor로 생성했으므로 모두 float으로 생성되었음도 확인 가능

tensor(1.) tensor(2.) tensor(7.)
tensor([3., 4., 5.]) tensor([5., 6.])


### 텐서 연산 및 차원 조작

* NumPy ndarray처럼 다양한 수학 연산 가능
* GPU 사용하면 더 빠른 연산 가능
* 단, 텐서 간 타입 다를 경우 연산 불가능 ((ex) FloatTensor & DoubleTensor)


* 차원 조작 (신경망에서 자주 다룸 -> 중요!)
  * 차원 변경하는 대표적인 방법 : view (NumPy reshape과 유사)
  * 텐서 결합 : stack, cat (다른 길이의 텐서를 하나로 병합)
  * 차원 교환 : t, transpose (행렬의 전치 & 차원 순서 변경)

In [ ]:
# 두 벡터 간 사칙연산
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])
print(w-v)

tensor([2, 2, 3])


In [ ]:
# 텐서의 차원 조작 
temp = torch.tensor([[1,2],[3,4]])
print(temp.shape)
print(temp.view(4,1))
print(temp.view(-1))
print(temp.view(1,-1))
print(temp.view(-1,1))

torch.Size([2, 2])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


## 2.2.2 데이터 준비 (예시 코드)

### 단순하게 파일을 불러와서 사용 : pandas library

In [ ]:
# 라이브러리 설치
(terminal) pip install pandas

# 라이브러리 호출
import pandas as pd
import torch
data = pd.read_csv('../class2.csv')

x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

### 커스텀 데이터셋을 만들어서 사용
* custom dataset : 데이터를 한 번에 다 부르지 않고 조금씩 나누어 불러서 사용하는 방식

In [ ]:
# CustomDataset 클래스 구현 형태

class CustomDataset(torch.utils.data.Dataset):
  def __init__(self):
    # 필요한 변수 선언
    # 데이터셋의 전처리
  def __len__(self):
    # 데이터셋의 길이(샘플의 수)
  def __getitem__(self,index):
    # 데이터셋에서 특정 데이터를 가져오는 함수 (index번째 데이터를 반환)
    # 반환되는 값은 텐서의 형태

In [ ]:
# 커스텀 데이터셋 구현 방법 예제
import pandas as pd
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset):
  def __init__(self,csv_file):
    self.label = pd.read_csv(csv_file)

### 파이토치에서 제공하는 데이터셋 사용
* torchvision : 파이토치에서 제공하는 데이터셋들이 모여 있는 패키지 : https://pytorch.org/vision/0.8/datasets.html
* requests 라이브러리
  * 파이토치에서 제공하는 데이터셋 내려받으려면 설치해야 함
  * HTTP 요청에 대한 처리를 위해 사용
  * 기본 내장 모듈 아니므로 별도 설치 필요 : pip insntall requests



In [1]:
pip install requests

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [25]:
# MNIST 데이터셋을 내려받는 예제
import torchvision.transforms as transforms

mnist_transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.5,),(1.0,))])

from torchvision.datasets import MNIST
import requests
download_root = "./content/drive/MyDrive/'Colab Notebooks'/'공부'/DLWithPytorch" # 내려받을 경로 지정

train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True)
valid_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)
test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting ./content/drive/MyDrive/'Colab Notebooks'/'공부'/DLWithPytorch/MNIST/raw/train-images-idx3-ubyte.gz to ./content/drive/MyDrive/'Colab Notebooks'/'공부'/DLWithPytorch/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting ./content/drive/MyDrive/'Colab Notebooks'/'공부'/DLWithPytorch/MNIST/raw/train-labels-idx1-ubyte.gz to ./content/drive/MyDrive/'Colab Notebooks'/'공부'/DLWithPytorch/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting ./content/drive/MyDrive/'Colab Notebooks'/'공부'/DLWithPytorch/MNIST/raw/t10k-images-idx3-ubyte.gz to ./content/drive/MyDrive/'Colab Notebooks'/'공부'/DLWithPytorch/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting ./content/drive/MyDrive/'Colab Notebooks'/'공부'/DLWithPytorch/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./content/drive/MyDrive/'Colab Notebooks'/'공부'/DLWithPytorch/MNIST/raw



## 2.2.3 모델 정의

### 단순 신경망을 정의하는 방법
* nn.Module을 상속받지 않는 매우 단순한 모델 만들 때 사용
* 구현이 쉽고 단순하다는 장점

In [ ]:
model = nn.Linear(in_features=1, out_features=1, bias=True)

### nn.Module()을 상속하여 정의하는 방법

### Sequential 신경망을 정의하는 방법

### 함수로 신경망을 정의하는 방법